### ISSUE TITLE
Webcam passthrough

### ISSUE THREAD

**Issue by mbach04** [EtixLabs/RTSPAllTheThings#35]
Document / support ability to pass in linux video device (/dev/video0).

**Comment by Gegonz** [comment]
Can be done with a new pipeline using https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good/html/gst-plugins-good-plugins-v4l2src.html

This needs to:
- Add a new input parsing: https://github.com/EtixLabs/RTSPAllTheThings/blob/master/src/parsing.cpp#L188
- Create the appropriate input pipeline: https://github.com/EtixLabs/RTSPAllTheThings/blob/master/src/pipeline.cpp#L111 using v4l2src https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good/html/gst-plugins-good-plugins-v4l2src.html

**Comment by Ullaakut** [comment]
We can do it but it will take some time for us as we currently have other priorities. If you can do it by yourself following the links provided above, your contribution would be very appreciated! :-)

Otherwise, expect the feature in the upcoming weeks

**Comment by mbach04** [comment]
PR #36 addresses this.

**Comment by mbach04** [comment]
It passes on my end, but the Travis CI script is failing.

**Comment by Ullaakut** [comment]
Awesome work. The CI failing is because I changed my docker credentials and forgot to update them for this repository's configuration. I'm restarting it, it should be fine and your PR will be merged!

Thank you for your quick and efficient contribution :)

**Comment by Ullaakut** [comment]
CI passes. @Gegonz will review your PR and test it manually and then we're good to go! :)

**Comment by Ullaakut** [comment]
Done in https://github.com/EtixLabs/RTSPAllTheThings/pull/36
