### ISSUE TITLE
End of file

### ISSUE THREAD

**Issue by lukeweston** [EtixLabs/RTSPAllTheThings#43]
When serving an RTSP stream from a video file, what is the default behavior at the end of the source file?

Does the stream restart from the start of the file, in an automatic infinite loop?

Is there any control over this loop behavior, or lack thereof?

**Comment by Ullaakut** [comment]
The default behavior is currently that it goes into an automatic infinite loop. Adding control over this behavior would be a welcome feature, but not one we are currently planning on working on.

If you'd like to contribute we can point you in the right direction and give you the necessary resources to implement this feature quite quickly :)

**Comment by lukeweston** [comment]
Thanks.
