### ISSUE TITLE
Continuous Error Msg: not authorized to see factory path

### ISSUE THREAD

**Issue by athvillar** [EtixLabs/RTSPAllTheThings#44]
Video cannot be displayed normally(Although sometimes can display). I use VLC on mac, server is docker container compiled with this newest code.

Is this because I continuously got this?
0:03:08.062553193     1 0x7f31a4002a30 ERROR             rtspclient rtsp-client.c:699:find_media: client 0x7f31ac03fe70: not authorized to see factory path /live.sdp
0:03:08.062580435     1 0x7f31a4002a30 ERROR             rtspclient rtsp-client.c:2239:handle_describe_request: client 0x7f31ac03fe70: no media

I am using the default parameters which are
  -e INPUT="/tmp/testv.avi" \
  -e GST_DEBUG=1 \
  -p 8554:8554 \
  -v /path-to-file/testv.avi:/tmp/testv.avi \

The source video do exists.

**Comment by Ullaakut** [comment]
Hi @athvillar,

In order to help you, I'll need to see the full logs of the docker container and to know what RTSP URL you're feeding to VLC.

**Comment by athvillar** [comment]
@Ullaakut 

Full logs: 
[root@120 ~]# docker logs rtspsv
                                               ▄██▄
                                               ▀███
                                                  █
                                 ▄▄▄▄▄            █
                                ▀▄    ▀▄          █
                            ▄▀▀▀▄ █▄▄▄▄█▄▄ ▄▀▀▀▄  █
                           █  ▄  █        █   ▄ █ █
                           ▀▄   ▄▀        ▀▄   ▄▀ █
                            █▀▀▀            ▀▀▀ █ █
                            █                   █ █
                  ▄▀▄▄▀▄    █  ▄█▀█▀█▀█▀█▀█▄    █ █
                  █▒▒▒▒█    █  █████████████▄   █ █
                  █▒▒▒▒█    █  ██████████████▄  █ █
                  █▒▒▒▒█    █   ██████████████▄ █ █
                  █▒▒▒▒█    █    ██████████████ █ █
                  █▒▒▒▒█    █   ██████████████▀ █ █
                  █▒▒▒▒█   ██   ██████████████  █ █
                  ▀████▀  ██▀█  █████████████▀  █▄█
                    ██   ██  ▀█  █▄█▄█▄█▄█▄█▀  ▄█▀
                    ██  ██    ▀█             ▄▀▓█
                    ██ ██      ▀█▀▄▄▄▄▄▄▄▄▄▀▀▓▓▓█
                    ████        █▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█
                    ███         █▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█
                    ██          █▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█
                    ██          █▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█
                    ██         ▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█
                    ██        ▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█
                    ██       ▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█▌
                    ██      ▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█▌
                    ██     ▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█▌
                    ██    ▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█▌
                    ______________________________                             
                    ___  __ \__  __/_  ___/__  __ \                            
                    __  /_/ /_  /  _____ \__  /_/ /                            
                    _  _, _/_  /   ____/ /_  ____/                             
                    /_/ |_| /_/    /____/ /_/                                  
                                                                               
__________________   _____________            _____________ _____                       
___    |__  /__  /   ___  __/__  /______      ___  __/__  /____(_)_____________ ________
__  /| |_  /__  /    __  /  __  __ \  _ \     __  /  __  __ \_  /__  __ \_  __ `/_  ___/
_  ___ |  / _  /     _  /   _  / / /  __/     _  /   _  / / /  / _  / / /  /_/ /_(__  ) 
/_/  |_/_/  /_/      /_/    /_/ /_/\___/      /_/    /_/ /_//_/  /_/ /_/_\__, / /____/  
                                                                        /____/          
Server configuration:
Address:	0.0.0.0
Port:		8554
Route:		/live.sdp
Username:	xxx
Password:	xxx

Input:		/tmp/testv.avi
Input type:	file

H264 encoding with:
Framerate:	25
Resolution:	1280x720

Launching stream with the following pipeline: ( appsrc name=mysrc ! decodebin ! videoscale ! video/x-raw,width=1280,height=720 ! videorate ! video/x-raw,framerate=25/1 ! capsfilter ! queue ! x264enc speed-preset=superfast ! rtph264pay name=pay0 pt=96  )
Stream ready at rtsp://hanq:hanq@0.0.0.0:8554/live.sdp
0:00:15.483013267     1 0x7f3214001680 ERROR             rtspclient rtsp-client.c:699:find_media: client 0x5600d0d691c0: not authorized to see factory path /live.sdp
0:00:15.483066344     1 0x7f3214001680 ERROR             rtspclient rtsp-client.c:2239:handle_describe_request: client 0x5600d0d691c0: no media
0:01:44.072868258     1 0x5600d0d57cf0 ERROR             rtspclient rtsp-client.c:699:find_media: client 0x5600d0d693a0: not authorized to see factory path /live.sdp
0:01:44.072913928     1 0x5600d0d57cf0 ERROR             rtspclient rtsp-client.c:2239:handle_describe_request: client 0x5600d0d693a0: no media
0:01:55.750482457     1 0x5600d0d57cf0 ERROR             rtspclient rtsp-client.c:699:find_media: client 0x5600d0d69490: not authorized to see factory path /live.sdp
0:01:55.750512727     1 0x5600d0d57cf0 ERROR             rtspclient rtsp-client.c:2239:handle_describe_request: client 0x5600d0d69490: no media
0:02:06.886225720     1 0x7f31ac002d40 ERROR             rtspclient rtsp-client.c:699:find_media: client 0x5600d0d69580: not authorized to see factory path /live.sdp
0:02:06.886251257     1 0x7f31ac002d40 ERROR             rtspclient rtsp-client.c:2239:handle_describe_request: client 0x5600d0d69580: no media
0:02:18.582688483     1 0x5600d0d57cf0 ERROR             rtspclient rtsp-client.c:699:find_media: client 0x7f31ac03fab0: not authorized to see factory path /live.sdp
0:02:18.582726440     1 0x5600d0d57cf0 ERROR             rtspclient rtsp-client.c:2239:handle_describe_request: client 0x7f31ac03fab0: no media


RTSP USL:
rtsp://xxx:xxx@xxx.xxx.xxx.xxx:8554/live.sdp

Pardon me to xxx my IP and pwd. Thank you.

**Comment by athvillar** [comment]
@Ullaakut 
Do I need to change the GST_DEBUG value to produce more logs?

**Comment by Ullaakut** [comment]
Here your issue is that you don't have any media to be read: `client.c:2239:handle_describe_request: client 0x5600d0d691c0: no media`

Are you sure that the path that you give in the arguments is right?

**Comment by Ullaakut** [comment]
Here is an example of command-line that might be useful:

`docker run -p 8554:8554 -e INPUT=/tmp/video.mp4 -v forgotten-object.mp4:/tmp/video.mp4 -e RTSP_PORT=8554 ullaakut/rtspatt`

I launched this command while having a file named `forgotten-object.mp4` in my current directory

**Comment by athvillar** [comment]
Thank you, but the media path is right
[root@120 ~]# docker exec -it rtspsv ls -l /tmp/testv.avi
-rw-r--r-- 1 root root 82153750 Jan 18 17:27 /tmp/testv.avi

Sometimes it can be displayed, most of time it can't.
I changed a docker server, everything became OK, no error logs. I don't know why. Anyway the problem disappeared. Thank you @Ullaakut .
