### ISSUE TITLE
Add TravisCI to check build and clang-fmt

### ISSUE THREAD

**Issue by jstoja** [EtixLabs/RTSPAllTheThings#6]
Right now it doesn't have code quality and automatic building to check PRs.

**Comment by Ullaakut** [comment]
Do you need it urgently? Ain't got no time to do that quickly yet.

**Comment by jstoja** [comment]
Not at all. Just think it would be a good idea to have it ;)

**Comment by Ullaakut** [comment]
Will do! :)

**Comment by Ullaakut** [comment]
I'll do it this week.

**Comment by Ullaakut** [comment]
TravisCI is now set, as well as Codacy with cppcheck, Hadolint, Vera++ and shellcheck.
